### ISSUE TITLE
btc_cassandra_streaming.py Exception

### ISSUE THREAD

**Issue by yaz1** [graphsense/graphsense-bitcoin-etl#2]
I am getting the below exception in btc_cassandra_streaming.py  line 415.

'StackData' object has no attribute 'hash'

**Comment by soad003** [comment]
Sorry i was not able to reproduce. If you can give more details and the issue is still there please open another issue.

**Comment by soad003** [comment]
i came across this bug while merging the of this repo into our new gs-lib repo. Please use the code there, this issue should be fixed there (in https://github.com/graphsense/graphsense-lib/commit/187a1ebbf3bed8dbf5c87c41f4429015956e111b)
